const colors = {
  white: '#FFFFFF',
  black: '#242424',
  colorInput: '#000000',
  colorBackground: '#2C3E50',
  colorBackground1: '#F2F2F2',
  colorBackground2: '#FAFAFA',
  colorBgLogin: '#7A8FA6',
  // colorBgLogin: '#C5B8FE',
  colorPrevious: 'black',
  colorBgRegister: '#667EEA',
  colorForgot: '#A3A3A3',
  colorNotification: '#2C3E50',
  colorGeneral: '#727580',
  colorTabBackground: '#1E252C',
  colorLabelInActive: '#7A8FA6',
  colorLabelActive: '#7A8FA6',
  colorLine: '#DADADA',
  colorLine1: '#757575',
  colorInstaOne: '#FF5858',
  colorInstaTwo: '#FB5895',
  colorFBOne: '#667EEA',
  colorFBTwo: '#667EEA',
  colorBtnGradientOne: '#003E7D',
  colorBtnGradientTwo: '#646AB1',
  colorTransparent: 'transparent',
  colorCountDownBackground: '#F7BB76',
  colorDiscountBackground: '#A0CADD',
  colorRightArrow: '#C2C4CA',
  colorTextNotification: '#ACB1C0',
  colorError: '#fc1f4a',
};
export default colors;
