const constants = {
  DEVICE_TOKEN: 'deviceToken',
  SKIP_INTRO: 'skipIntro',
  IS_LOGIN: 'isLogin',
  USER: 'user',
  INIT_CGU: 'init',
  CLAIMED: 'CLAIMED',
  REDEEMED: 'REDEEMED',
  SALE: 'SALE',
  BOUGHT: 'BOUGHT',
  UNUSED: 'UNUSED',
  CREDENTIALS: 'credentials',
  MATRIX_PREPROD: 'https://preprod-matrix.reetags.com',
  matrixProd: 'https://preprod-matrix.reetags.com',
  NumberOfTimes: 'NumberOfTimesOpened',
  IsRateDone: 'IsRateDone',
  BrandImage: 'BrandImage',
  BrandImageCat: 'BrandImageCat',
  UUID: 'UUID',
  LAST_SEARCH_DATA: 'LAST_SEARCH_DATA',
  RECENT_PRODUCT: 'recent_product',
  RECENT_BRAND: 'recent_brand',
  CAT_EXPLORER: 'feedExplorerCat',
  POINTS: 'PointsSelection',
  SELECTION: 'selection',
  STATISTIQUE: 'statistique',
  THEME: 'theme',
};
export default constants;
