export const POST_LOGIN_REQUEST = "POST_LOGIN_REQUEST";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILURE = "POST_LOGIN_FAILURE";

export const DO_LOGOUT = "POST_LOGIN_FAILURE";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const POST_SOCIAL_LOGIN_REQUEST = "POST_SOCIAL_LOGIN_REQUEST";
export const POST_SOCIAL_LOGIN_SUCCESS = "POST_SOCIAL_LOGIN_SUCCESS";
export const POST_SOCIAL_LOGIN_FAILURE = "POST_SOCIAL_LOGIN_FAILURE";

export const POST_REGISTER_REQUEST = "POST_REGISTER_REQUEST";
export const POST_REGISTER_SUCCESS = "POST_REGISTER_SUCCESS";
export const POST_REGISTER_FAILURE = "POST_REGISTER_FAILURE";

export const DELETEINBOUTIQUE = "DELETEINBOUTIQUE";
export const SCREENFOCUSTAB = "SCREENFOCUSTAB";
export const SET_VIDEO_URL= "SET_VIDEO_URL";

export const GET_GENERAL_FEEDS_REQUEST = "GET_GENERAL_FEEDS_REQUEST";
export const GET_GENERAL_FEEDS_SUCCESS = "GET_GENERAL_FEEDS_SUCCESS";
export const GET_GENERAL_FEEDS_FAILURE = "GET_GENERAL_FEEDS_FAILURE";

export const GET_FOLLOWING_FEEDS_REQUEST = "GET_FOLLOWING_FEEDS_REQUEST";
export const GET_FOLLOWING_FEEDS_SUCCESS = "GET_FOLLOWING_FEEDS_SUCCESS";
export const GET_FOLLOWING_FEEDS_FAILURE = "GET_FOLLOWING_FEEDS_FAILURE";

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_TOP_OFFERS_REQUEST = "GET_TOP_OFFERS_REQUEST";
export const GET_TOP_OFFERS_SUCCESS = "GET_TOP_OFFERS_SUCCESS";
export const GET_TOP_OFFERS_FAILURE = "GET_TOP_OFFERS_FAILURE";

export const GET_CATALOGUE_REQUEST = "GET_CATALOGUE_REQUEST";
export const GET_CATALOGUE_SUCCESS = "GET_CATALOGUE_SUCCESS";
export const GET_CATALOGUE_FAILURE = "GET_CATALOGUE_FAILURE";

export const POST_FEED_COMMENT_REQUEST = "POST_FEED_COMMENT_REQUEST";
export const POST_FEED_COMMENT_SUCCESS = "POST_FEED_COMMENT_SUCCESS";
export const POST_FEED_COMMENT_FAILURE = "POST_FEED_COMMENT_FAILURE";

export const GET_FEED_REFRESH = "GET_FEED_REFRESH";

export const ADD_PRODUCT_TO_SHOP_REQUEST = "ADD_PRODUCT_TO_SHOP_REQUEST";
export const ADD_PRODUCT_TO_SHOP_SUCCESS = "ADD_PRODUCT_TO_SHOP_SUCCESS";
export const ADD_PRODUCT_TO_SHOP_FAILURE = "ADD_PRODUCT_TO_SHOP_FAILURE";

export const ADD_REETAGS_PRODUCT_TO_SHOP_REQUEST = "ADD_REETAGS_PRODUCT_TO_SHOP_REQUEST";
export const ADD_REETAGS_PRODUCT_TO_SHOP_SUCCESS = "ADD_REETAGS_PRODUCT_TO_SHOP_SUCCESS";
export const ADD_REETAGS_PRODUCT_TO_SHOP_FAILURE = "ADD_REETAGS_PRODUCT_TO_SHOP_FAILURE";

export const USER_FOLLOW_REQUEST = "USER_FOLLOW_REQUEST";
export const USER_FOLLOW_SUCCESS = "USER_FOLLOW_SUCCESS";
export const USER_FOLLOW_FAILURE = "USER_FOLLOW_FAILURE";

export const GET_BRAND_IMAGE_REQUEST = "GET_BRAND_IMAGE_REQUEST";
export const GET_BRAND_IMAGE_SUCCESS = "GET_BRAND_IMAGE_SUCCESS";
export const GET_BRAND_IMAGE_SUCCESS2 = "GET_BRAND_IMAGE_SUCCESS2";
export const GET_BRAND_IMAGE_FAILURE = "GET_BRAND_IMAGE_FAILURE";

export const GET_REGISTRATION_TAGS_REQUEST = "GET_REGISTRATION_TAGS_REQUEST";
export const GET_REGISTRATION_TAGS_SUCCESS = "GET_REGISTRATION_TAGS_SUCCESS";
export const GET_REGISTRATION_TAGS_FAILURE = "GET_REGISTRATION_TAGS_FAILURE";

export const SET_USER_DATA_REQUEST = "SET_USER_DATA_REQUEST";
export const SET_USER_DATA_SUCCESS = "SET_USER_DATA_SUCCESS";
export const SET_USER_DATA_FAILURE = "SET_USER_DATA_FAILURE";

export const ADD_NEW_ACTIVITY_REQUEST = "ADD_NEW_ACTIVITY_REQUEST";
export const ADD_NEW_ACTIVITY_SUCCESS = "ADD_NEW_ACTIVITY_SUCCESS";
export const ADD_NEW_ACTIVITY_FAILURE = "ADD_NEW_ACTIVITY_FAILURE";

export const GET_OTHER_USER_PROFILE_REQUEST = "GET_OTHER_USER_PROFILE_REQUEST";
export const GET_OTHER_USER_PROFILE_SUCCESS = "GET_OTHER_USER_PROFILE_SUCCESS";
export const GET_OTHER_USER_PROFILE_FAILURE = "GET_OTHER_USER_PROFILE_FAILURE";

export const ADD_USER_REVIEW_REQUEST = "ADD_USER_REVIEW_REQUEST";
export const ADD_USER_REVIEW_SUCCESS = "ADD_USER_REVIEW_SUCCESS";
export const ADD_USER_REVIEW_FAILURE = "ADD_USER_REVIEW_FAILURE";

export const GET_BRAND_LIST_REQUEST = "GET_BRAND_LIST_REQUEST";
export const GET_BRAND_LIST_SUCCESS = "GET_BRAND_LIST_SUCCESS";
export const GET_BRAND_LIST_FAILURE = "GET_BRAND_LIST_FAILURE";

export const GET_MEMBER_LIST_REQUEST = "GET_MEMBER_LIST_REQUEST";
export const GET_MEMBER_LIST_SUCCESS = "GET_MEMBER_LIST_SUCCESS";
export const GET_MEMBER_LIST_FAILURE = "GET_MEMBER_LIST_FAILURE";

export const GET_BRAND_PRODUCT_LIST_REQUEST = "GET_BRAND_PRODUCT_LIST_REQUEST";
export const GET_BRAND_PRODUCT_LIST_SUCCESS = "GET_BRAND_PRODUCT_LIST_SUCCESS";
export const GET_BRAND_PRODUCT_LIST_FAILURE = "GET_BRAND_PRODUCT_LIST_FAILURE";

export const GET_USER_FOLLOWER_LIST_REQUEST = "GET_USER_FOLLOWER_LIST_REQUEST";
export const GET_USER_FOLLOWER_LIST_SUCCESS = "GET_USER_FOLLOWER_LIST_SUCCESS";
export const GET_USER_FOLLOWER_LIST_FAILURE = "GET_USER_FOLLOWER_LIST_FAILURE";

export const GET_OTHER_USER_FOLLOWER_LIST_REQUEST = "GET_OTHER_USER_FOLLOWER_LIST_REQUEST";
export const GET_OTHER_USER_FOLLOWER_LIST_SUCCESS = "GET_OTHER_USER_FOLLOWER_LIST_SUCCESS";
export const GET_OTHER_USER_FOLLOWER_LIST_FAILURE = "GET_OTHER_USER_FOLLOWER_LIST_FAILURE";


export const GET_USER_FOLLOWING_LIST_REQUEST = "GET_USER_FOLLOWING_LIST_REQUEST";
export const GET_USER_FOLLOWING_LIST_SUCCESS = "GET_USER_FOLLOWING_LIST_SUCCESS";
export const GET_USER_FOLLOWING_LIST_FAILURE = "GET_USER_FOLLOWING_LIST_FAILURE";

export const GET_OTHER_USER_FOLLOWING_LIST_REQUEST = "GET_OTHER_USER_FOLLOWING_LIST_REQUEST";
export const GET_OTHER_USER_FOLLOWING_LIST_SUCCESS = "GET_OTHER_USER_FOLLOWING_LIST_SUCCESS";
export const GET_OTHER_USER_FOLLOWING_LIST_FAILURE = "GET_OTHER_USER_FOLLOWING_LIST_FAILURE";

export const GET_USER_REVIEW_LIST_REQUEST = "GET_USER_REVIEW_LIST_REQUEST";
export const GET_USER_REVIEW_LIST_SUCCESS = "GET_USER_REVIEW_LIST_SUCCESS";
export const GET_USER_REVIEW_LIST_FAILURE = "GET_USER_REVIEW_LIST_FAILURE";

export const GET_OTHER_USER_REVIEW_LIST_REQUEST = "GET_OTHER_USER_REVIEW_LIST_REQUEST";
export const GET_OTHER_USER_REVIEW_LIST_SUCCESS = "GET_OTHER_USER_REVIEW_LIST_SUCCESS";
export const GET_OTHER_USER_REVIEW_LIST_FAILURE = "GET_OTHER_USER_REVIEW_LIST_FAILURE";

export const UPDATE_USER_ID_CONNECT = "UPDATE_USER_ID_CONNECT";
export const UPDATE_TOKEN_USER = "UPDATE_TOKEN_USER";
export const UPDATE_USERNAME = "UPDATE_USERNAME";


export const GET_USER_PRODUCT_LIST_REQUEST = "GET_USER_PRODUCT_LIST_REQUEST";
export const GET_USER_PRODUCT_LIST_SUCCESS = "GET_USER_PRODUCT_LIST_SUCCESS";
export const GET_USER_PRODUCT_LIST_FAILURE = "GET_USER_PRODUCT_LIST_FAILURE";

export const GET_OTHER_USER_PRODUCT_LIST_REQUEST = "GET_OTHER_USER_PRODUCT_LIST_REQUEST";
export const GET_OTHER_USER_PRODUCT_LIST_SUCCESS = "GET_OTHER_USER_PRODUCT_LIST_SUCCESS";
export const GET_OTHER_USER_PRODUCT_LIST_FAILURE = "GET_OTHER_USER_PRODUCT_LIST_FAILURE";

export const GET_USER_PRODUCT_LIST_OFFER_REQUEST = "GET_USER_PRODUCT_LIST_OFFER_REQUEST";
export const GET_USER_PRODUCT_LIST_OFFER_SUCCESS = "GET_USER_PRODUCT_LIST_OFFER_SUCCESS";
export const GET_USER_PRODUCT_LIST_OFFER_FAILURE = "GET_USER_PRODUCT_LIST_OFFER_FAILURE";

export const GET_USER_REETAGS_PRODUCT_LIST_REQUEST = "GET_USER_REETAGS_PRODUCT_LIST_REQUEST";
export const GET_USER_REETAGS_PRODUCT_LIST_SUCCESS = "GET_USER_REETAGS_PRODUCT_LIST_SUCCESS";
export const GET_USER_REETAGS_PRODUCT_LIST_FAILURE = "GET_USER_REETAGS_PRODUCT_LIST_FAILURE";

export const GET_OTHER_USER_REETAGS_PRODUCT_LIST_REQUEST = "GET_OTHER_USER_REETAGS_PRODUCT_LIST_REQUEST";
export const GET_OTHER_USER_REETAGS_PRODUCT_LIST_SUCCESS = "GET_OTHER_USER_REETAGS_PRODUCT_LIST_SUCCESS";
export const GET_OTHER_USER_REETAGS_PRODUCT_LIST_FAILURE = "GET_OTHER_USER_REETAGS_PRODUCT_LIST_FAILURE";

export const GET_USER_REETAGS_PRODUCT_LIST_OFFER_REQUEST = "GET_USER_REETAGS_PRODUCT_LIST_OFFER_REQUEST";
export const GET_USER_REETAGS_PRODUCT_LIST_OFFER_SUCCESS = "GET_USER_REETAGS_PRODUCT_LIST_OFFER_SUCCESS";
export const GET_USER_REETAGS_PRODUCT_LIST_OFFER_FAILURE = "GET_USER_REETAGS_PRODUCT_LIST_OFFER_FAILURE";

export const USER_WITHDRAW_MONEY_REQUEST = "USER_WITHDRAW_MONEY_REQUEST";
export const USER_WITHDRAW_MONEY_SUCCESS = "USER_WITHDRAW_MONEY_SUCCESS";
export const USER_WITHDRAW_MONEY_FAILURE = "USER_WITHDRAW_MONEY_FAILURE";

export const GET_PRODUCT_REFRESH = "GET_PRODUCT_REFRESH";
export const GET_REETAGS_PRODUCT_REFRESH = "GET_REETAGS_PRODUCT_REFRESH";
export const GET_USER_PROFILE_REFRESH = "GET_USER_PROFILE_REFRESH";

export const ADD_VIDEO_LINK_REQUEST = "ADD_VIDEO_LINK_REQUEST";
export const ADD_VIDEO_LINK_SUCCESS = "ADD_VIDEO_LINK_SUCCESS";
export const ADD_VIDEO_LINK_FAILURE = "ADD_VIDEO_LINK_FAILURE";

export const CHANGE_PROFILE_REQUEST = "CHANGE_PROFILE_REQUEST";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_FAILURE = "CHANGE_PROFILE_FAILURE";

export const UPDATE_IS_MODAL_VISIBLE = "UPDATE_IS_MODAL_VISIBLE";

export const UPDATE_IS_TAPBAR_VISIBLE = "UPDATE_IS_TAPBAR_VISIBLE";

export const UPDATE_PAGE = "UPDATE_PAGE";

export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST";
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS";
export const GET_NOTIFICATION_FAILURE = "GET_NOTIFICATION_FAILURE";

export const POST_NOTIFICATION_REQUEST = "POST_NOTIFICATION_REQUEST";
export const POST_NOTIFICATION_SUCCESS = "POST_NOTIFICATION_SUCCESS";
export const POST_NOTIFICATION_FAILURE = "POST_NOTIFICATION_FAILURE";

export const UPDATE_RS_FIELD_REQUEST = "UPDATE_RS_FIELD_REQUEST";
export const UPDATE_RS_FIELD_SUCCESS = "UPDATE_RS_FIELD_SUCCESS";
export const UPDATE_RS_FIELD_FAILURE = "UPDATE_RS_FIELD_FAILURE";

export const SET_NOTIFICATION_DATA = "SET_NOTIFICATION_DATA";

export const GET_BADGE_REQUEST = "GET_BADGE_REQUEST";
export const GET_BADGE_SUCCESS = "GET_BADGE_SUCCESS";
export const GET_BADGE_FAILURE = "GET_BADGE_FAILURE";

export const POST_GALLERY_REQUEST = "POST_GALLERY_REQUEST";
export const POST_GALLERY_SUCCESS = "POST_GALLERY_SUCCESS";
export const POST_GALLERY_FAILURE = "POST_GALLERY_FAILURE";

export const GET_RECOMMENDED_USER_REQUEST = "GET_RECOMMENDED_USER_REQUEST";
export const GET_RECOMMENDED_USER_SUCCESS = "GET_RECOMMENDED_USER_SUCCESS";
export const GET_RECOMMENDED_USER_FAILURE = "GET_RECOMMENDED_USER_FAILURE";

export const POST_ADD_VIEW_REQUEST = "POST_ADD_VIEW_REQUEST";
export const POST_ADD_VIEW_SUCCESS = "POST_ADD_VIEW_SUCCESS";
export const POST_ADD_VIEW_FAILURE = "POST_ADD_VIEW_FAILURE";

export const POST_ADD_SHARE_REQUEST = "POST_ADD_SHARE_REQUEST";
export const POST_ADD_SHARE_SUCCESS = "POST_ADD_SHARE_SUCCESS";
export const POST_ADD_SHARE_FAILURE = "POST_ADD_SHARE_FAILURE";

export const ADDID = "ADD_ID";
export const INITID = "INIT_ID";
export const DELETEID = "DELETE_ID";

export const BUBBLENOTIFICATIONMESSAGE = "BUBBLENOTIFICATIONMESSAGE";
export const BUBBLENOTIFICATIONAUTRE = "BUBBLENOTIFICATIONAUTRE";
export const BUBBLENOTIFICATIONCONCOURS = "BUBBLENOTIFICATIONCONCOURS";
export const REMOVEBUBBLENOTIFICATIONAUTRE = "REMOVEBUBBLENOTIFICATIONAUTRE";
export const REMOVEBUBBLENOTIFICATIONCONCOURS = "REMOVEBUBBLENOTIFICATIONCONCOURS";
export const REMOVEBUBBLENOTIFICATIONMESSAGE = "REMOVEBUBBLENOTIFICATIONMESSAGE";
export const INITBUBBLENOTIFICATIONCONCOURS = "INITBUBBLENOTIFICATIONCONCOURS";
export const INITBUBBLENOTIFICATIONMESSAGE = "INITBUBBLENOTIFICATIONMESSAGE";
export const INITBUBBLENOTIFICATIONAUTRE = "INITBUBBLENOTIFICATIONAUTRE";

export const INITABBUBBLE = "INITABBUBBLE";

export const INITURLREGISTER = "INITURLREGISTER";

export const SETGOOGLEPRODUCTSET = "SETGOOGLEPRODUCTSET";

export const SETUSERTOTALPOINT = "SETUSERTOTALPOINT";

export const APPISINIT = "APPISINIT";
export const SETUSERPOINT = "SETUSERPOINT";

export const SETSTATISTICVIDEO = "SETSTATISTICVIDEO";
export const SETSTATISTICPRODUCT = "SETSTATISTICPRODUCT";
export const SETSTATISTICPAGE = "SETSTATISTICPAGE";
export const SETSTATISTICUSER = "SETSTATISTICUSER";
export const SETSTATISTICSEARCH = "SETSTATISTICSEARCH";
export const SETSTATISTICADD = "SETSTATISTICADD";
export const SETSTATISTICINIT = "SETSTATISTICINIT";

export const SETUSERDATA = "SETUSERDATA";
export const DELETEUSERDATA = "DELETEUSERDATA";

export const USER_CRED = "USER_CRED";
export const CONNECT = "CONNECT";